services:

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 80:80
    environment:
      APACHE_RUN_USER: "#33"
      WORDPRESS_DB_HOST: '${DATABASE_HOST}'
      WORDPRESS_DB_USER: '${DATABASE_USER}'
      WORDPRESS_DB_PASSWORD: '${DATABASE_PASSWORD}'
      WORDPRESS_DB_NAME: '${DATABASE_NAME}'
    volumes:
      - wordpress:/var/www/html
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 81:80
    environment:
      - PMA_ARBITRARY=1

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: '${DATABASE_NAME}'
      MYSQL_USER: '${DATABASE_USER}'
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
